# Generated by Django 5.2.9 on 2026-01-06 20:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimationinput',
            name='drewno_m3',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='estimationinput',
            name='druk_m2',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='estimationinput',
            name='konstrukcja_kg',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='estimationinput',
            name='koszty_pozostale',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='estimationinput',
            name='led_mb',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='estimationinput',
            name='naklad_szt',
            field=models.PositiveIntegerField(default=1, help_text='Dodatnia liczba całkowita', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='estimationinput',
            name='objetosc_m3',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='estimationinput',
            name='plyta_m2',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='estimationinput',
            name='rodzaj_displaya',
            field=models.CharField(choices=[('ekspozytor_pmma', 'Ekspozytor PMMA'), ('ekspozytor_tworzywowy', 'Ekspozytor tworzywowy'), ('maly_naladowy', 'Mały display naladowy'), ('potykacz', 'Potykacz'), ('regal_qpd', 'Regal QPD'), ('regal_hpd', 'Regal HPD'), ('regal_pd', 'Regal PD'), ('paleciak_qpd', 'Paleciak QPD'), ('paleciak_hpd', 'Paleciak HPD'), ('paleciak_pd', 'Paleciak PD'), ('owijka_pd', 'Owijka paletowa'), ('kaseton', 'Kaseton'), ('wyspa', 'Wyspa'), ('druciak', 'Druciak'), ('pozostale', 'Pozostałe')], default='ekspozytor_pmma', max_length=50),
        ),
        migrations.AlterField(
            model_name='estimationinput',
            name='rodzaj_tworzywa',
            field=models.CharField(blank=True, choices=[('HIPS', 'HIPS'), ('PMMA', 'PMMA'), ('PET', 'PET'), ('PC', 'PC'), ('ABS', 'ABS'), ('NAKLEJKA', 'NAKLEJKA'), ('GUMA', 'GUMA'), ('TKANINA', 'TKANINA')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='estimationinput',
            name='sklejka_m3',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='estimationinput',
            name='stopien_skomplikowania',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='estimationinput',
            name='tworzywa_m2',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='estimationresult',
            name='user_price',
            field=models.FloatField(default=0),
        ),
    ]
