# Generated by Django 5.2.9 on 2026-01-10 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimations', '0002_alter_estimationinput_drewno_m3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimationinput',
            name='rodzaj_displaya',
            field=models.CharField(choices=[('ekspozytor_tworzywowy', 'Ekspozytor tworzywowy'), ('naladowy', 'Display naladowy'), ('potykacz', 'Potykacz'), ('regal', 'Regał QPD/HPD/PD'), ('paleciak', 'Paleciak QPD/HPD/PD'), ('owijka', 'Owijka paletowa'), ('kaseton', 'Kaseton'), ('wyspa', 'Wyspa'), ('druciak', 'Druciak'), ('pozostale', 'Pozostałe')], default='ekspozytor_pmma', max_length=50),
        ),
    ]
